import type { Concept } from "./types";

// Foundations and evidence. Every entry names the document it was written against.
export const foundationsAndEvidence: Concept[] = [
  {
    id: "framework",
    title: "Framework",
    group: "foundations",
    oneSentence: "Compound Design itself: a loop, a set of resources, and an evidence system that is allowed to say no.",
    plain: "A way of working that a design engineer installs into the coding agent they already use. It structures work as a loop and keeps what was learned where the next run will find it.",
    why: "Without a shared structure, useful practice lives in individual habits and resets every session.",
    analogy: "A studio's way of working — not any one project, but the habits that make every project easier than the last.",
    inPractice: "You install one plugin. Your agent gains six loop procedures, four around them, five specialists and six agents, plus the discipline about what may be claimed.",
    inCompound: "The framework's own infrastructure lives under compound-design/; the artifacts produced by using it live under docs/. The two trees are deliberately separate.",
    failsWithout: "Every project starts from zero. Judgment spent once is spent again.",
    technical: "An open plugin of skills and agents, installed via host manifests (.claude-plugin, .codex-plugin, .cursor-plugin) over one canonical skills/ directory, with a registry, contract suites, a learning ledger and a pre-registered benchmark.",
    related: ["resource", "skill", "agent"],
    source: { path: "STRATEGY.md" },
    status: "v0.3.0-alpha.1 candidate; stable evidence baseline v0.2.1",
    aliases: ["compound design", "the loop", "work system", "sistema de trabalho", "método"],
    queries: ["what is compound design", "o que é compound design", "how is this different from a prompt", "what do I actually install"],
  },
  {
    id: "resource",
    title: "Resource",
    group: "foundations",
    oneSentence: "Anything a procedure uses — a skill, an agent, a registry, a contract, a checker — that is registered and carries an evidence level.",
    plain: "The unit of the system. If it can be named, versioned and tested, it is a resource.",
    why: "Evidence has to attach to something. Making every skill and agent a resource means each one has a level, a construction score and a record of what it still owes.",
    analogy: "An instrument in a lab: it has a serial number, a calibration record, and a note saying what it has and has not been checked for.",
    inPractice: "Interface Review is a resource. So is the finding contract it emits and the registry that lists it.",
    inCompound: "Twenty-one active resources — fifteen skills and six agents — plus three superseded ones kept for their historical evidence.",
    failsWithout: "Capability floats free of accountability. Something 'works' with no way to ask how anyone knows.",
    technical: "An entry in compound-design/registry/resource-registry.json with id, publicName, kind, status, path, version, cdqi, cel, runtimeUplift, evidenceDebt and provenance; validated against a JSON Schema by cd:registry.",
    related: ["skill", "agent", "resource-registry", "cel", "cdqi"],
    source: { path: "compound-design/registry/resource-registry.json" },
    status: "24 registered, 21 active",
    aliases: ["recurso", "asset", "tool"],
    queries: ["what counts as a resource", "is an agent a resource", "o que é um recurso"],
  },
  {
    id: "skill",
    title: "Skill",
    group: "foundations",
    oneSentence: "A procedure: how a piece of work is done.",
    plain: "A written procedure the agent follows — when to use it, when not to, what it may write, what it must never do, and when it is finished.",
    why: "A procedure that is written down can be tested, versioned and improved. One that lives in someone's head cannot.",
    analogy: "A checklist a pilot runs — not because they do not know how to fly, but because the list does not forget.",
    inPractice: "cd-frame, cd-verify, cd-interface-review. Each lives at skills/<id>/SKILL.md and is read directly by every host.",
    inCompound: "Fifteen skills, each with twelve required sections that a deterministic suite checks. Skill = procedure; agent = specialist; resource = anything a procedure uses.",
    failsWithout: "Every run re-invents the steps, and skips the one that mattered.",
    technical: "A SKILL.md with YAML frontmatter (name, description, argument-hint) and fixed sections: When to use, When not to use, Scope, Inputs, Procedure, Write authority, Artifact rule, Output contract, Forbidden, Missing dependency, Completion, Provenance.",
    related: ["agent", "resource", "framework"],
    source: { path: "skills/cd-frame/SKILL.md" },
    status: "15 active, all E1",
    aliases: ["procedure", "procedimento", "habilidade", "SKILL.md"],
    queries: ["what is a skill", "difference between a skill and an agent", "qual a diferença entre skill e agent"],
  },
  {
    id: "agent",
    title: "Agent",
    group: "foundations",
    oneSentence: "A specialist dispatched into its own context to do scoped work and return a result.",
    plain: "A worker sent off with one job and a clean desk. It does the job and reports back; it does not chat and it does not wander.",
    why: "Some judgments should not be made by whoever happens to be orchestrating. A specialist with a bounded context makes them better and cannot quietly widen its own authority.",
    analogy: "A consultant brought in for one question, who leaves a written answer and does not touch the files.",
    inPractice: "interface-reviewer, motion-reviewer, evidence-reviewer. Each is under sixty lines and points at the skill that owns the procedure.",
    inCompound: "Six agents. An agent that restates its skill's procedure fails a deterministic test, because a copy would drift.",
    failsWithout: "Either the orchestrator makes every judgment itself, or specialists accumulate copies of procedures that silently diverge.",
    technical: "A markdown file under agents/ with frontmatter (name, description, tools) and eight sections: Specialism, Dispatch when, Do not dispatch when, Procedure, Tool policy, Returns, Boundaries, Provenance. Enforced ≤ 60 lines.",
    related: ["skill", "resource", "routing"],
    source: { path: "agents/interface-reviewer.md" },
    status: "6 active, all E1",
    aliases: ["specialist", "subagent", "especialista", "agente"],
    queries: ["what is an agent here", "why are agents so short", "por que os agentes são tão curtos"],
  },
  {
    id: "upstream",
    title: "Upstream",
    group: "foundations",
    oneSentence: "Open-source work that informed a resource — a source and a provenance obligation, never a runtime dependency.",
    plain: "Other people's published work that Compound Design learned from. It is credited, pinned to an exact commit, and never loaded when the plugin runs.",
    why: "Building on mature ideas is better than rewriting them from zero; pretending you did not is dishonest, and depending on them at runtime is fragile.",
    analogy: "The papers a study cites: essential to how it was designed, not part of the apparatus.",
    inPractice: "Interface Review's heuristics were informed by Jakub Krehel's skills; Motion Review's by Emil Kowalski's; the architecture by Every's Compound Engineering. Each is pinned by commit.",
    inCompound: "The installed plugin clones nothing. The pinned upstream is fetched only for one benchmark condition — comparing against direct upstream use — and never ships.",
    failsWithout: "Either quiet copying with no credit, or a plugin that breaks when a repository it depends on changes.",
    technical: "Recorded in compound-design/SOURCES.md with repository, pinned SHA and licence; drift from the pin is recorded, never followed (e2 fetch-upstream).",
    related: ["provenance", "upstream-drift", "pin"],
    source: { path: "compound-design/SOURCES.md" },
    status: "three pinned sources; no runtime dependency",
    aliases: ["source", "fonte", "origem", "referência"],
    queries: ["where did this come from", "does the plugin download other repos", "de onde vem esse conhecimento"],
  },
  {
    id: "provenance",
    title: "Provenance",
    group: "foundations",
    oneSentence: "The record of where a resource's ideas and material came from, and what that obliges.",
    plain: "Who influenced this, which exact version, under which licence, and what we owe them. Visible when useful; never implying they endorse us.",
    why: "A claim about a resource's quality means little without knowing what it was built from. And borrowed work carries obligations.",
    analogy: "The provenance of a painting: who owned it, when, and how we know — without the previous owner vouching for the current one.",
    inPractice: "Every skill ends with a Provenance section. The site shows 'Built within Compound Design. Informed by …' and links to the full record.",
    inCompound: "No personal upstream name is used as an active resource name. Public names are authorial; provenance stays explicit underneath.",
    failsWithout: "Credit is lost, licences are violated, and 'informed by' quietly becomes 'endorsed by'.",
    technical: "A provenance field per registry entry, a Provenance section per skill and agent, NOTICE at the repository root and compound-design/SOURCES.md with pinned SHAs and licences.",
    related: ["upstream", "resource"],
    source: { path: "NOTICE" },
    status: "recorded for every active resource",
    aliases: ["attribution", "atribuição", "proveniência", "credit", "licence"],
    queries: ["who made this", "is this endorsed by the original authors", "isso é endossado pelos autores originais"],
  },
  {
    id: "cdqi",
    title: "CDQI",
    group: "evidence",
    oneSentence: "A 0–10 construction score: is this resource well built?",
    plain: "How well the resource is put together — is its job clear, are its boundaries explicit, are its instructions ordered, can it be tested, can it be maintained. It says nothing about whether it works.",
    why: "'Well built' and 'proven to help' are different questions, and one number cannot answer both. CDQI answers the first so that it can never be mistaken for the second.",
    analogy: "A building inspection: the wiring is to code and the structure is sound. That is not the same as people liking to live there.",
    inPractice: "Quality Gate holds 8.75; Resource Lab 8.65; AI Interaction Review 8.35. The v0.3 resources show a dash: their construction has not been audited yet, and a score is never assumed.",
    inCompound: "Seven weighted dimensions, judged and written down by a person. Never raised because runtime results look good.",
    failsWithout: "A single score gets read as proof — the exact failure v0.1 had and v0.2 was built to remove.",
    technical: "CDQI = Σ(dimension × weight) over Scope & contract 15%, Routing & boundaries 15%, Domain grounding 15%, Instruction design 15%, Output & actionability 15%, Evalability 15%, Maintainability & provenance 10%. Null until a construction audit is written.",
    related: ["cel", "quality-gate", "evidence-debt"],
    source: { path: "compound-design/quality/CD-QUALITY-INDEX.md" },
    status: "audited for three carried-over resources; null for the rest",
    aliases: ["construction quality", "quality index", "qualidade de construção", "score", "nota"],
    queries: ["what does the score mean", "why is the score a dash", "o que significa a nota", "is a high score proof it works"],
  },
  {
    id: "cel",
    title: "CEL",
    group: "evidence",
    oneSentence: "Compound Evidence Level, E0–E4: how strongly has this resource's effectiveness actually been demonstrated?",
    plain: "A ladder of evidence. Each rung says what kind of check has been done and, crucially, what you are allowed to say because of it.",
    why: "Claims drift upward on their own. A ladder with fixed rungs makes every claim checkable against the artifact that earned it.",
    analogy: "Clinical evidence grades: an expert opinion, a controlled trial and years of field data are all 'evidence', and nobody confuses them.",
    inPractice: "Every Compound resource is at E1: its declared contracts hold under deterministic checks. Nothing is at E2, because no controlled runtime comparison has been run.",
    inCompound: "CEL moves only when new evidence is produced. It never moves because construction improved, a model praised the output, or a vendor's tool was used.",
    failsWithout: "'Tested' means whatever the speaker wants it to mean.",
    technical: "E0 inspection · E1 deterministic contracts · E2 controlled runtime · E3 independent · E4 field. Each level names the evidence required and the allowed claim class.",
    related: ["e0", "e1", "e2", "e3", "e4", "cdqi", "runtime-uplift"],
    source: { path: "compound-design/quality/CD-EVIDENCE-LEVELS.md" },
    status: "maximum E1 across all resources",
    aliases: ["evidence level", "nível de evidência", "evidence maturity", "E-level"],
    queries: ["how do I know if it works", "como saber se funciona", "what has been tested", "what does E1 mean", "is this validated"],
  },
  {
    id: "e0",
    title: "E0 — Inspected",
    group: "evidence",
    oneSentence: "Someone read it carefully. Nothing has been run.",
    plain: "The resource has been reviewed by eye — its prose, its sources, its boundaries. No executable check exists yet.",
    why: "Every resource starts somewhere. E0 is the honest name for 'it looks right'.",
    analogy: "A recipe that reads well. Nobody has cooked it.",
    inPractice: "Every v0.3 resource entered the registry at E0 and moved to E1 only after the contract suite ran, in a separate commit.",
    inCompound: "Allowed claim: well-constructed / validation pending.",
    failsWithout: "'Looks right' gets presented as 'tested'.",
    technical: "Evidence: prose or static review, source and provenance inspection; no executed evaluation artifact required.",
    related: ["cel", "e1"],
    source: { path: "compound-design/quality/CD-EVIDENCE-LEVELS.md", note: "E0 — Inspection" },
    status: "no active resource remains at E0",
    aliases: ["inspection", "inspeção", "reviewed only"],
    queries: ["what is E0", "what does inspected mean"],
  },
  {
    id: "e1",
    title: "E1 — Deterministic contracts",
    group: "evidence",
    oneSentence: "Machines checked that the resource declares and satisfies its own contract, the same way every time.",
    plain: "There is an executable test with a recorded pass/fail. It proves the resource is shaped as promised. It does not prove the shape helps anyone.",
    why: "A contract you can run is the first thing that separates a real resource from a nicely written prompt.",
    analogy: "A car passes its safety inspection. It has not been driven on a track against another car.",
    inPractice: "The v0.3 contract suite: 26 checks across skills, agents and discoverability, all passed, recorded in v0.3-contract-eval.json.",
    inCompound: "Allowed claim: contract-tested. Forbidden: proven to improve outcomes. This is the current ceiling for every resource.",
    failsWithout: "Nothing distinguishes a resource whose contract holds from one that merely describes itself well.",
    technical: "Evidence: executable or reproducible contract checks, static invariants, deterministic regression assertions, an artifact with pass/fail results.",
    related: ["cel", "e2", "self-test", "mutation-test"],
    source: { path: "compound-design/quality/CD-EVIDENCE-LEVELS.md", note: "E1 — Deterministic" },
    status: "current level for all 21 active resources",
    aliases: ["contract-tested", "deterministic", "determinístico", "testado por contrato"],
    queries: ["what does E1 mean", "what has actually been tested", "o que foi testado de verdade", "is E1 enough"],
  },
  {
    id: "e2",
    title: "E2 — Controlled runtime",
    group: "evidence",
    oneSentence: "The resource was run against a baseline on the same tasks, repeatedly, and the difference was recorded.",
    plain: "The first level that can say the resource helps. It requires a fair comparison: same model, same tasks, with and without the resource, more than once.",
    why: "Everything below E2 is about the resource's shape. E2 is the first evidence about its effect.",
    analogy: "The track day: the same driver, the same course, two cars, several laps each — and the times written down.",
    inPractice: "Pre-registered and frozen for Interface Review and Quality Gate. Never executed: it requires paid model runtime, which the project has refused to assume.",
    inCompound: "Allowed claim at E2: demonstrated uplift in tested scope. No Compound resource may be described as E2 until controlled baseline artifacts exist.",
    failsWithout: "Effectiveness is narrated instead of measured.",
    technical: "Evidence: a relevant baseline, the same representative tasks, candidate versus baseline or previous version, repeated nondeterministic runs, outcome and routing deltas, cost and latency where relevant.",
    related: ["cel", "e1", "e3", "benchmark", "baseline", "runtime-uplift", "pre-registration"],
    source: { path: "compound-design/quality/CD-EVIDENCE-LEVELS.md", note: "E2 — Controlled runtime" },
    status: "pre-registered, not executed",
    aliases: ["controlled runtime", "runtime evidence", "benchmark level", "evidência de runtime"],
    queries: ["why hasn't E2 been run", "por que o E2 não foi executado", "when will it be tested for real", "what would it take to prove it works"],
  },
  {
    id: "e3",
    title: "E3 — Independent",
    group: "evidence",
    oneSentence: "Someone or something outside the original setup reached the same conclusion.",
    plain: "A different model family, a separate evaluator, or a blinded human agrees with the E2 result.",
    why: "A result produced and judged by the same setup can be an artifact of that setup. Independence is what rules that out.",
    analogy: "A second lab reproduces the experiment.",
    inPractice: "Not reached. Note the rule: using a vendor's model to grade is not vendor certification, and the same vendor's different model is not an independent model family.",
    inCompound: "Allowed claim: independently corroborated in tested scope.",
    failsWithout: "One setup's blind spots become the evidence.",
    technical: "E2 plus at least one of: an independent or cross-model grader, a separate evaluator framework or provider, a blinded human comparison, a representative external benchmark. The artifact must identify evaluator, version and rubric.",
    related: ["cel", "e2", "e4", "judge", "blinding"],
    source: { path: "compound-design/quality/CD-EVIDENCE-LEVELS.md", note: "E3 — Independent" },
    status: "not reached",
    aliases: ["independent validation", "cross-model", "validação independente"],
    queries: ["what is independent evidence", "does using a different model count"],
  },
  {
    id: "e4",
    title: "E4 — Field evidence",
    group: "evidence",
    oneSentence: "It has been used for real, across versions and model changes, and its failures are on record.",
    plain: "The highest level: not a test, a history. Real use, regressions tracked, failures kept, rollbacks possible.",
    why: "Tests are a model of reality. Field evidence is reality.",
    analogy: "A bridge that has carried traffic through twenty winters and whose inspection reports are public.",
    inPractice: "Not reached by anything here.",
    inCompound: "Allowed claim: field-proven in defined scope. The scope can widen; the level cannot go higher.",
    failsWithout: "Nothing is ever known to survive contact with real work.",
    technical: "Requires real-use evidence over time, regression history across multiple versions, a meaningful failure corpus, stable behaviour across runtime and model changes, rollback and version history.",
    related: ["cel", "e3"],
    source: { path: "compound-design/quality/CD-EVIDENCE-LEVELS.md", note: "E4 — Field evidence" },
    status: "not reached",
    aliases: ["field evidence", "evidência de campo", "in production"],
    queries: ["has anyone used this for real", "alguém usou isso de verdade"],
  },
  {
    id: "runtime-uplift",
    title: "Runtime uplift",
    group: "evidence",
    oneSentence: "The measured difference a resource makes when a model actually runs with it versus without it.",
    plain: "Does the agent do better work with this resource loaded than without it, on the same task, the same model, more than once? That difference — if it exists — is uplift.",
    why: "It is the only thing that would justify saying a resource helps. Everything else is about how it is built.",
    analogy: "The difference between a runner's time with and without a coach — on the same course, measured, not felt.",
    inPractice: "For every Compound resource the answer is 'not measured'. The site, the registry and the release notes all say so, because the comparison has never been run.",
    inCompound: "Uplift can only be established at E2 or above, against a relevant baseline, with repeated runs. It is never inferred from a good-looking output.",
    failsWithout: "'It feels better' becomes the evidence.",
    technical: "Reported as paired per-task differences between conditions (C − A, C − B), with pre-registered thresholds: +5 points on the frozen rubric, non-inferiority within 2, no critical-recall loss.",
    related: ["e2", "baseline", "paired-difference", "benchmark"],
    source: { path: "compound-design/quality/EVIDENCE-DEBT.md" },
    status: "not measured for every resource",
    aliases: ["uplift", "improvement", "melhoria", "ganho", "effect"],
    queries: ["does it actually help", "isso realmente ajuda", "how much better is it", "quanto melhor fica"],
  },
  {
    id: "evidence-debt",
    title: "Evidence debt",
    group: "evidence",
    oneSentence: "The explicit gap between what a resource is built to do and what has been shown.",
    plain: "A list, per resource, of what it is meant to do and what has never been demonstrated. Written down so that unmeasured capability is never narrated as impact.",
    why: "Debt you can see gets repaid. Debt nobody names becomes marketing.",
    analogy: "A ledger of promises made and not yet kept — kept in public.",
    inPractice: "Interface Review's debt: runtime behaviour in real work, routing accuracy, effect on outcomes. Every v0.3 resource owes all of its runtime evidence.",
    inCompound: "Preparation repays no debt. Neither do a higher self-score, a new prompt revision, model praise, screenshots or passing the examples used to write the resource.",
    failsWithout: "The gap between built and proven closes in prose instead of in evidence.",
    technical: "A per-resource evidenceDebt array in the registry and a repayment order in compound-design/quality/EVIDENCE-DEBT.md.",
    related: ["cel", "runtime-uplift", "cdqi"],
    source: { path: "compound-design/quality/EVIDENCE-DEBT.md" },
    status: "recorded for every active resource",
    aliases: ["dívida de evidência", "unproven", "what is missing"],
    queries: ["what hasn't been proven", "o que ainda não foi provado", "what is still owed"],
  },
  {
    id: "quality-gate",
    title: "Quality Gate",
    group: "evidence",
    oneSentence: "The procedure that decides whether a resource has earned the claim being made for it — and evaluates the evaluator first.",
    plain: "Before a resource is promoted or described as better, the gate asks what artifact supports that, whether the grader itself was checked, and which level the artifact actually earns.",
    why: "Someone has to be allowed to say no. A gate that only ever approves is decoration.",
    analogy: "A referee who also has to show their own eyesight test.",
    inPractice: "A skill with a strong contract and no runtime evidence gets a good construction score and stays at E1. The gate refuses to let one number borrow from the other.",
    inCompound: "One of the three resources carried unchanged from v0.2, holding its audited construction score of 8.75.",
    failsWithout: "Promotion follows enthusiasm.",
    technical: "skills/cd-quality-gate/SKILL.md: CDQI and CEL sections, required evaluation layers, meta-evaluation, decision states, promotion defaults, output contract.",
    related: ["cdqi", "cel", "evidence-debt", "resource-value-audit"],
    source: { path: "skills/cd-quality-gate/SKILL.md" },
    status: "active, E1, CDQI 8.75",
    aliases: ["gate", "promotion gate", "portão de qualidade"],
    queries: ["who decides if a resource is good enough", "quem decide se um recurso está pronto"],
  },
  {
    id: "resource-registry",
    title: "Resource Registry",
    group: "evidence",
    oneSentence: "The one machine-readable list of every resource, what it is for, where it came from, and what evidence it has.",
    plain: "A single file that names each resource, its version, its level, its construction score, its job, its non-goals and what it still owes. Everything else reads from it.",
    why: "Facts stated in many places drift apart. Facts stated once and validated by a schema do not.",
    analogy: "A ship's manifest: one list, checked at every port.",
    inPractice: "This site's version, level and counts are read from the registry at build time. A route cannot say E2 while the registry says E1.",
    inCompound: "Validated against a JSON Schema by cd:registry and by lint rules with mutation self-tests. Executing the schema is how a long-standing violation of it was found in v0.3.",
    failsWithout: "Every document restates the facts, and one of them is wrong.",
    technical: "compound-design/registry/resource-registry.json with release, releaseStage, pluginVersion, evidencePolicy and 24 resource entries; schema-checked, lint-checked with 9 mutation fixtures.",
    related: ["resource", "cel", "cdqi"],
    source: { path: "compound-design/registry/resource-registry.json" },
    status: "24 entries, schema-validated",
    aliases: ["registry", "registro", "catálogo", "manifest"],
    queries: ["where is the list of resources", "onde está a lista de recursos", "single source of truth"],
  },
  {
    id: "resource-value-audit",
    title: "Resource Value Audit",
    group: "evidence",
    oneSentence: "The question 'if this resource disappeared and we used the upstream directly, what would actually be lost?' — answered from run artifacts, with removal as a valid result.",
    plain: "A deliberate check that a Compound resource adds something real over the open-source work it was built from. If the honest answer is 'almost nothing', the resource is simplified or removed.",
    why: "More Compound code is not a success metric. A wrapper that only renames upstream work is maintenance without value.",
    analogy: "Asking whether the middleman earns his cut.",
    inPractice: "Seven concrete properties are checked after the pilot: routing, integration, contract, evidence, learning, system context, specialisation. It is scheduled and has not run.",
    inCompound: "Pre-registered in the E2 plan. 'Authorship preserves nothing.'",
    failsWithout: "Resources accumulate because deleting one feels like losing.",
    technical: "compound-design/quality/WRAPPER-VALUE-AUDIT.md decision test (upstream capability, Compound addition, duplication risk, testable hypothesis, removal test) and E2-PILOT-PLAN.md §16.",
    related: ["upstream", "benchmark", "conditions-abc"],
    source: { path: "compound-design/quality/WRAPPER-VALUE-AUDIT.md" },
    status: "pre-registered, scheduled after the pilot",
    aliases: ["wrapper value audit", "removal test", "auditoria de valor"],
    queries: ["why not just use the original skills", "por que não usar as skills originais", "what does compound add"],
  },
];
