import type { Concept } from "./types";

// The harness, its measurements, and the tooling. Written against the E2 scripts, plan and CI.
export const harnessMeasurementTooling: Concept[] = [
  {
    id: "dry-run",
    title: "Dry run",
    group: "harness",
    oneSentence: "Running the whole benchmark pipeline with a deterministic stand-in instead of a model, to prove the machinery works before spending anything.",
    plain: "Everything runs — tasks, workspaces, assertions, blinding, aggregation — except the expensive part, which is replaced by a fake that echoes predictable text.",
    why: "The first time a pipeline runs should not be the time it costs money.",
    analogy: "A fire drill.",
    inPractice: "e2 dry-run uses an exec provider that echoes; assertions run against the echo; classification, blinding and aggregation are exercised end to end.",
    inCompound: "The dry run once revealed that failed assertions were being miscounted as provider errors — fixed before any model was involved.",
    failsWithout: "The first paid run is spent debugging the harness.",
    technical: "quality/e2/promptfoo-dryrun.yaml with an exec: provider; e2 dry-run; results classified scored | truncated | route_invalid | error.",
    related: ["self-test", "promptfoo", "anti-billing-guard"],
    source: { path: "compound-design/quality/e2/RUNBOOK.md" },
    status: "runs in CI",
    aliases: ["ensaio", "simulação", "rehearsal", "echo provider"],
    queries: ["how do you test the test without paying", "como testar o teste sem pagar"],
  },
  {
    id: "self-test",
    title: "Self-test",
    group: "harness",
    oneSentence: "A check that the checks work: deliberately broken inputs that must be rejected.",
    plain: "Each guard in the system is tested by feeding it something it must refuse. If it accepts, the guard is broken — and the build fails.",
    why: "A guard that silently stopped working is worse than no guard: everyone trusts it.",
    analogy: "Testing the smoke alarm by making smoke.",
    inPractice: "The E2 harness rejects 32 planted mutations; the framework tooling passes 40 checks; the registry lint rejects 9 mutations. All run in CI.",
    inCompound: "A guard that flags a rule as a violation is itself a bug — one that recurred once, and is now tested in both directions.",
    failsWithout: "Guards decay without anyone noticing.",
    technical: "e2 self-test, cd selftest, cd-lint --self-test; fixtures under scripts/self-test-fixtures/.",
    related: ["mutation-test", "e1", "ci"],
    source: { path: "compound-design/quality/e2/scripts/e2.mjs" },
    status: "32/32, 40/40, 9/9",
    aliases: ["autoteste", "auto-teste", "meta-test"],
    queries: ["how do you know the checks themselves work", "como saber que as verificações funcionam"],
  },
  {
    id: "mutation-test",
    title: "Mutation test",
    group: "harness",
    oneSentence: "Introducing a specific defect on purpose to prove a check catches it.",
    plain: "Take a valid file, break one thing — remove a required section, edit a frozen snapshot, set the paid-runtime flag — and confirm the guard refuses it.",
    why: "'The test passed' proves little. 'The test fails when it should' is what makes a test worth having.",
    analogy: "Planting a fake defect on the assembly line to see whether inspection catches it.",
    inPractice: "'Edited legacy snapshot rejected.' 'Agent that restates its skill rejected.' 'Workflow that sets the paid-runtime flag rejected.'",
    inCompound: "Both directions are required: the violation must fail, and a comment that merely names the rule must pass.",
    failsWithout: "Tests that can never fail accumulate and reassure.",
    technical: "Self-test cases apply a mutation to a copy of the input and assert the guard's exit code and message.",
    related: ["self-test", "learning-ledger"],
    source: { path: "compound-design/learning/LEDGER.md", note: "CD-20260909-012" },
    status: "used by all three self-tests",
    aliases: ["mutation", "mutação", "planted defect", "negative test"],
    queries: ["what is a mutation test", "o que é teste de mutação"],
  },
  {
    id: "workspace-isolation",
    title: "Workspace isolation",
    group: "harness",
    oneSentence: "Every run gets its own disposable directory with exactly the files its condition allows, and nothing else.",
    plain: "The model under test cannot see the answer key, another condition's files, or a previous run's output, because none of them are in its folder.",
    why: "A model that can read the ground truth is not being tested.",
    analogy: "Separate exam rooms.",
    inPractice: "Condition A's workspace has fixtures only; C's adds the Compound resource; the ground truth lives outside every workspace.",
    inCompound: "e2 workspaces builds them from the pinned snapshot; e2 validate checks that no workspace leaks a forbidden file.",
    failsWithout: "Contamination, and a result nobody can trust.",
    technical: "quality/e2/.workspaces/ (gitignored); per-condition file lists; validated for leakage.",
    related: ["leakage", "fixture", "conditions-abc"],
    source: { path: "compound-design/quality/e2/RUNBOOK.md" },
    status: "implemented and validated",
    aliases: ["isolation", "isolamento", "sandbox", "clean room"],
    queries: ["can the model see the answers", "o modelo consegue ver as respostas"],
  },
  {
    id: "leakage",
    title: "Leakage",
    group: "harness",
    oneSentence: "Any way information that should be hidden reaches the thing being tested or the thing doing the scoring.",
    plain: "The answer key in the workspace. A condition label in a blinded output. A holdout task used to design a fix. All leakage.",
    why: "Leakage makes results look better than they are, silently.",
    analogy: "The exam paper left on the photocopier.",
    inPractice: "The blind gate once caught the harness's own echo provider printing its condition into the output. That was leakage, and it was rejected.",
    inCompound: "Holdouts stay unseen; workspaces are isolated; blinded payloads are scanned for identifiers; prompts were scrubbed of eval framing and resource names.",
    failsWithout: "The benchmark measures how much leaked.",
    technical: "Identifier redaction, workspace validation, prompt hygiene, task digests.",
    related: ["holdout", "workspace-isolation", "blinding"],
    source: { path: "compound-design/quality/e2/E2-PILOT-PLAN.md", note: "§5 prompt hygiene; §6" },
    status: "guarded",
    aliases: ["contamination", "vazamento", "contaminação"],
    queries: ["what is contamination", "o que é vazamento"],
  },
  {
    id: "routing",
    title: "Routing",
    group: "harness",
    oneSentence: "Deciding which resource — or none — a piece of work should go to.",
    plain: "Not every request needs every stage. A copy fix does not need Frame. A backend migration does not need Interface Review. Routing is getting that right.",
    why: "A specialist applied to the wrong problem produces confident nonsense.",
    analogy: "Triage.",
    inPractice: "Three near-miss tasks in the pilot test exactly this: a backend migration, a motion-only request and an AI auto-deletion, none of which Interface Review should take.",
    inCompound: "The orchestrator's only job is routing. Routing gates in the benchmark pass or fail; they never score.",
    failsWithout: "Everything goes through every stage, or the wrong specialist answers.",
    technical: "Deterministic routing gates per task; e2 aggregate counts route_invalid runs; agents declare 'Dispatch when' and 'Do not dispatch when'.",
    related: ["route-invalid", "agent"],
    source: { path: "agents/compound-design.md" },
    status: "contract-tested; runtime accuracy not measured",
    aliases: ["dispatch", "roteamento", "triage", "delegation"],
    queries: ["how does it decide which skill to use", "como decide qual skill usar"],
  },
  {
    id: "route-invalid",
    title: "Route invalid",
    group: "harness",
    oneSentence: "A run classification: the resource took a task it should have declined, or declined one it should have taken.",
    plain: "One of four outcomes a run can have. It is excluded from scoring and counted — because too many of them is itself a failure condition.",
    why: "A wrong route is not a low score; it is a different kind of failure and has to be counted as one.",
    analogy: "A wrong-number call: not a bad conversation, a non-conversation.",
    inPractice: "More than five route-invalid or error runs out of twenty-seven is a pre-registered condition under which Compound loses.",
    inCompound: "e2 aggregate refuses to exclude runs for any other reason.",
    failsWithout: "Wrong routes hide inside average scores.",
    technical: "Classification scored | truncated | route_invalid | error; condition 6 in E2-PILOT-PLAN.md §15.",
    related: ["routing", "truncated", "aggregate"],
    source: { path: "compound-design/quality/e2/E2-PILOT-PLAN.md", note: "§10 Telemetry; §15" },
    status: "defined",
    aliases: ["misroute", "rota inválida", "wrong route"],
    queries: ["what happens if it answers the wrong question"],
  },
  {
    id: "truncated",
    title: "Truncated",
    group: "harness",
    oneSentence: "A run that hit its turn or budget limit before finishing; scored on what it emitted.",
    plain: "The model ran out of allowed turns or money. Whatever it produced is scored as is — not thrown away, not completed for it.",
    why: "Throwing away truncated runs would quietly favour the condition that takes longest.",
    analogy: "Pens down when the bell rings; what is on the page is marked.",
    inPractice: "Limits are fixed and identical across conditions: 12 turns, one dollar per run.",
    inCompound: "The aggregate step refuses to exclude truncated runs.",
    failsWithout: "Slow conditions get a free retry.",
    technical: "max_turns 12, max_budget_usd 1.0; classification truncated; self-test 'aggregate refuses to exclude truncated runs'.",
    related: ["route-invalid", "aggregate"],
    source: { path: "compound-design/quality/e2/E2-PILOT-PLAN.md", note: "§10" },
    status: "defined",
    aliases: ["cut off", "truncado", "ran out of budget"],
    queries: ["what if the model runs out of time"],
  },
  {
    id: "aggregate",
    title: "Aggregate",
    group: "measurement",
    oneSentence: "Turning many scored runs into a decision by the pre-registered rules — and nothing else.",
    plain: "Once every run is scored, the harness computes the means, the per-task differences and the intervals, checks each 'Compound loses' condition, and reports. No hand adjustment.",
    why: "The moment results exist, judgment becomes advocacy. Aggregation is done by code written before results existed.",
    analogy: "Counting the ballots with the rules printed on the box.",
    inPractice: "e2 aggregate reads blinded scores plus the unblind key, evaluates the ten conditions, and labels every statistic EXPLORATORY / DESCRIPTIVE.",
    inCompound: "It refuses to exclude any run except by the four allowed classifications.",
    failsWithout: "The analysis is rerun until it agrees.",
    technical: "e2 aggregate --scores=…; outputs summary.json with means, ranges, sign counts, bootstrap intervals and condition verdicts.",
    related: ["paired-difference", "bootstrap", "sign-test", "confidence-interval"],
    source: { path: "compound-design/quality/e2/E2-PILOT-PLAN.md", note: "§12, §15" },
    status: "implemented; never given real scores",
    aliases: ["agregação", "summary", "results"],
    queries: ["how are the results combined", "como os resultados são combinados"],
  },
  {
    id: "paired-difference",
    title: "Paired difference",
    group: "measurement",
    oneSentence: "The score with the resource minus the score without it, on the same task.",
    plain: "Instead of comparing averages across everything, compare each task with itself: C on task 3 minus A on task 3. Tasks differ wildly in difficulty; pairing removes that.",
    why: "It is the first thing read in the interpretation order, ahead of any statistic.",
    analogy: "Before-and-after on the same patient, not two different patients.",
    inPractice: "Nine paired differences for interface review — one per task — reported individually with min, max and sign counts.",
    inCompound: "Effective N is nine tasks; repeats are within-task and do not add tasks.",
    failsWithout: "Task difficulty masquerades as resource effect.",
    technical: "Per-task C − A and C − B on the primary rubric; interpretation priority 1 in E2-PILOT-PLAN.md §12.",
    related: ["aggregate", "sign-test", "bootstrap", "runtime-uplift"],
    source: { path: "compound-design/quality/e2/E2-PILOT-PLAN.md", note: "§12" },
    status: "defined",
    aliases: ["diferença pareada", "per-task delta", "delta"],
    queries: ["how do you compare with and without", "como comparar com e sem"],
  },
  {
    id: "bootstrap",
    title: "Bootstrap",
    group: "measurement",
    oneSentence: "Resampling the tasks many times to see how much the result would wobble with a different draw of tasks.",
    plain: "Take the nine tasks, draw nine with replacement, compute the mean difference; repeat thousands of times. The spread of those means is how uncertain the estimate is.",
    why: "Nine tasks is a small sample. The bootstrap says so in numbers instead of adjectives.",
    analogy: "Re-running the tournament with slightly different teams to see whether the same side keeps winning.",
    inPractice: "A 90% bootstrap interval over tasks is reported, labelled exploratory.",
    inCompound: "Condition 4: if the interval of C − B contains −2 and its upper bound is below +5, Compound has not shown enough.",
    failsWithout: "A single mean is reported as if it were certain.",
    technical: "Bootstrap over tasks, 90% interval; forbidden wording: 'statistically significant'.",
    related: ["confidence-interval", "aggregate", "paired-difference"],
    source: { path: "compound-design/quality/e2/E2-PILOT-PLAN.md", note: "§12, §15 condition 4" },
    status: "implemented",
    aliases: ["resampling", "reamostragem"],
    queries: ["how sure are you with only nine tasks", "quão confiável é com poucas tarefas"],
  },
  {
    id: "sign-test",
    title: "Sign test",
    group: "measurement",
    oneSentence: "Counting on how many tasks the resource won, regardless of by how much.",
    plain: "If Compound beat the baseline on eight of nine tasks, that pattern is informative even before looking at the sizes. If it won on three, no average rescues it.",
    why: "Averages can be carried by one big win. Counting wins cannot.",
    analogy: "Match wins, not total points.",
    inPractice: "Condition 3: C > B on three or fewer of nine tasks means Compound loses.",
    inCompound: "Reported as sign counts alongside paired differences.",
    failsWithout: "One outlier task decides the result.",
    technical: "Sign counts of positive paired differences; E2-PILOT-PLAN.md §15 condition 3.",
    related: ["paired-difference", "aggregate"],
    source: { path: "compound-design/quality/e2/E2-PILOT-PLAN.md", note: "§15" },
    status: "defined",
    aliases: ["win count", "contagem de vitórias"],
    queries: ["what if it wins big on one task and loses the rest"],
  },
  {
    id: "confidence-interval",
    title: "Confidence interval",
    group: "measurement",
    oneSentence: "A range the true difference plausibly lies in, given how few tasks there are.",
    plain: "Not one number but a range. With nine tasks the range is wide — roughly ±5.5 points — which is why the pilot calls its thresholds decision rules, not significance claims.",
    why: "Reporting a point estimate without its range invites reading noise as signal.",
    analogy: "'Between 20 and 30 minutes' is more honest than '25 minutes'.",
    inPractice: "The +5 promotion threshold sits at the edge of what nine tasks can resolve; the −2 non-inferiority margin is not testable at this N. The plan says so.",
    inCompound: "Forbidden wording: statistically significant, proven, validated, reliable uplift.",
    failsWithout: "Noise gets promoted.",
    technical: "90% bootstrap interval over tasks; E2-PILOT-PLAN.md §12 statistical limitations.",
    related: ["bootstrap", "paired-difference"],
    source: { path: "compound-design/quality/e2/E2-PILOT-PLAN.md", note: "§12" },
    status: "defined, exploratory",
    aliases: ["intervalo de confiança", "uncertainty", "margin"],
    queries: ["how precise is the measurement", "qual a margem de erro"],
  },
  {
    id: "promptfoo",
    title: "Promptfoo",
    group: "tooling",
    oneSentence: "The open-source evaluation harness the benchmark is built on — pinned, and run here only with a deterministic provider.",
    plain: "A tool for running the same prompt many times across conditions and asserting things about the outputs. In this repository it has never been pointed at a model.",
    why: "Repeated fresh runs, structured assertions and cost telemetry across providers are exactly what a controlled comparison needs, and building them from scratch would be its own project.",
    analogy: "Lab equipment bought, calibrated and never yet switched on with a live sample.",
    inPractice: "Pinned at one version; every loadable config passes a schema check (promptfoo validate, schema only); the dry run uses an exec provider that echoes.",
    inCompound: "Using Promptfoo is not 'Promptfoo certified' — vendor-endorsement wording is forbidden by the protocol.",
    failsWithout: "A bespoke harness with its own untested bugs.",
    technical: "promptfoo 0.122.2; evaluateOptions.repeat 3; --no-cache; exec: providers only in loadable configs; runtime templates guarded.",
    related: ["dry-run", "anti-billing-guard", "pin"],
    source: { path: "compound-design/quality/e2/environment.json", note: "harness" },
    status: "pinned; zero-model configuration",
    aliases: ["harness", "eval tool"],
    queries: ["what runs the benchmark", "o que roda o benchmark"],
  },
  {
    id: "playwright",
    title: "Playwright",
    group: "tooling",
    oneSentence: "A browser automation library, used locally to derive deterministic facts about a rendered fixture.",
    plain: "It opens the fixture in a real browser and records things that are true or false: is there horizontal overflow at 320 pixels, is every clickable element reachable by keyboard, does focus have a visible outline.",
    why: "Those facts become ground truth that does not depend on anyone's opinion.",
    analogy: "A tape measure for web pages.",
    inPractice: "The rendered admin-page task's observations file; and this site's own checks at five viewports.",
    inCompound: "Runs locally, no network, no model. Its observations carry provenance in the ground truth.",
    failsWithout: "Layout and reachability facts are asserted from memory.",
    technical: "playwright-core 1.63.0, local Chromium; e2 fixtures; scripts/site-check.mjs.",
    related: ["axe-core", "fixture", "ground-truth"],
    source: { path: "compound-design/quality/e2/scripts/e2.mjs", note: "fixtures" },
    status: "pinned",
    aliases: ["browser automation", "automação de navegador"],
    queries: ["how do you check layout automatically"],
  },
  {
    id: "axe-core",
    title: "axe-core",
    group: "tooling",
    oneSentence: "An automated accessibility checker, used as a signal — never as proof of accessibility.",
    plain: "It finds a class of accessibility defects mechanically: missing labels, insufficient contrast, broken roles. What it does not find is not thereby fine.",
    why: "Automated checks are cheap and consistent. They are also incomplete, and pretending otherwise is the failure mode.",
    analogy: "A spell-checker: catches a lot, proves nothing about whether the sentence makes sense.",
    inPractice: "Violations become expected items with 'axe' provenance in the ground truth. Best-practice rules are unscored — neither rewarded nor penalised.",
    inCompound: "Its results are supplementary; accessibility is never claimed proven from axe alone.",
    failsWithout: "Either no automated signal, or a false sense of coverage.",
    technical: "axe-core 4.13.0, run inside Playwright; resultTypes violations; impact recorded.",
    related: ["playwright", "ground-truth", "fixture"],
    source: { path: "NOTICE", note: "E2 benchmark harness" },
    status: "pinned",
    aliases: ["axe", "accessibility checker", "verificador de acessibilidade"],
    queries: ["is the site accessible", "o site é acessível", "does passing axe mean accessible"],
  },
  {
    id: "ci",
    title: "CI",
    group: "tooling",
    oneSentence: "The automated checks that run on every change — all deterministic, none of them calling a model.",
    plain: "Three jobs: the framework's gates, the site's build, and the benchmark harness's self-tests. If any fails, the change does not merge.",
    why: "Discipline that only exists when someone remembers is not discipline.",
    analogy: "The turnstile.",
    inPractice: "Registry, contract suite, plugin package, claim guard, self-tests; typecheck, lint, build; harness install, upstream pin check, frozen-snapshot equivalence, 32 mutations, validate, dry run.",
    inCompound: "CI is provably free of paid model runtime: two independent self-tests assert that no workflow sets the paid-runtime flag or invokes a model.",
    failsWithout: "Guards are run when convenient.",
    technical: ".github/workflows/ci.yml: work-system, app, e2-harness; zero-model guarantee checked by e2 self-test and cd selftest.",
    related: ["self-test", "anti-billing-guard"],
    source: { path: ".github/workflows/ci.yml" },
    status: "three jobs, zero model",
    aliases: ["pipeline", "integração contínua", "checks"],
    queries: ["what runs on every commit", "o que roda a cada commit"],
  },
  {
    id: "sha",
    title: "SHA",
    group: "tooling",
    oneSentence: "A fingerprint of exact content — a commit, a file, a task set — so 'the same' can be proved rather than assumed.",
    plain: "A long hexadecimal string that changes if a single byte changes. Two things with the same SHA are the same thing.",
    why: "'We used the same version' is a claim. Matching SHAs are evidence.",
    analogy: "A fingerprint.",
    inPractice: "Upstream repositories are pinned by commit SHA. Task sets carry SHA-256 digests. The legacy snapshot's manifest lists a SHA per file, checked against the baseline commit.",
    inCompound: "This site's own generated content records the SHA of each canonical file it was built from.",
    failsWithout: "Nobody can prove what was tested.",
    technical: "Git commit SHA-1 for pins; SHA-256 for task digests and the resource manifest.",
    related: ["pin", "upstream-drift", "c0-c1"],
    source: { path: "compound-design/quality/e2/legacy-resources/v0.2/RESOURCE-MANIFEST.json" },
    status: "used throughout",
    aliases: ["hash", "digest", "commit hash", "fingerprint"],
    queries: ["what is a sha", "how do you prove two files are identical"],
  },
  {
    id: "pin",
    title: "Pin",
    group: "tooling",
    oneSentence: "Fixing a dependency or source to one exact version so results stay comparable.",
    plain: "Instead of 'the latest', a specific commit or version number. It never moves on its own.",
    why: "If the input moves, yesterday's result and today's are about different things.",
    analogy: "A photograph, not a live feed.",
    inPractice: "Jakub Krehel's skills at 267330e1; Every's plugin at b36047e1; promptfoo 0.122.2; playwright-core 1.63.0; axe-core 4.13.0.",
    inCompound: "Pins never change automatically. Drift is recorded, never followed.",
    failsWithout: "The benchmark silently tests something else.",
    technical: "SOURCES.md pinned SHAs; e2 fetch-upstream verifies SHA and LICENSE; environment.json records drift.",
    related: ["sha", "upstream-drift", "upstream"],
    source: { path: "compound-design/SOURCES.md" },
    status: "all sources pinned",
    aliases: ["pinned version", "versão fixada", "lock"],
    queries: ["what version was tested", "qual versão foi testada"],
  },
  {
    id: "upstream-drift",
    title: "Upstream drift",
    group: "tooling",
    oneSentence: "The upstream repository has moved past the pinned commit.",
    plain: "The open-source source Compound learned from has new commits. That fact is recorded; the pin does not move.",
    why: "Knowing the source has changed matters. Following it automatically would change the experiment underneath the results.",
    analogy: "Noting that a new edition of the textbook is out, while the course keeps using the edition the exam was written for.",
    inPractice: "Checked on the day of writing: no drift for either pinned source.",
    inCompound: "Recorded only. Moving a pin is a deliberate, versioned decision.",
    failsWithout: "Condition B tests a different upstream every week.",
    technical: "e2 fetch-upstream compares remote HEAD to pinned_sha and writes drift: true|false.",
    related: ["pin", "sha", "upstream"],
    source: { path: "compound-design/quality/e2/environment.json", note: "upstream" },
    status: "no drift recorded",
    aliases: ["drift", "deriva"],
    queries: ["what if the original repo changes"],
  },
  {
    id: "anti-billing-guard",
    title: "Anti-billing guard",
    group: "tooling",
    oneSentence: "The lock that refuses to run any model unless paid runtime is explicitly authorised.",
    plain: "The benchmark's runtime command checks for one specific environment variable set to one exact value. Without it, it stops with a message and exits. Nothing is spent by accident.",
    why: "The project was prepared under a rule of zero cost. A rule is only real if the software enforces it.",
    analogy: "The safety on a firearm.",
    inPractice: "Blocked: E2 model runtime requires explicit paid-runtime authorization. A value of 'yes' instead of 'YES' is still blocked.",
    inCompound: "Self-tested in both directions, and CI is scanned to prove no workflow sets the flag.",
    failsWithout: "A cost rule that depends on nobody making a mistake.",
    technical: "E2_PAID_RUNTIME_CONFIRMED must equal YES; exit 2 otherwise; self-tests 'paid-runtime without flag → exit 2' and 'flag != exactly YES → blocked'.",
    related: ["ci", "self-test", "e2"],
    source: { path: "compound-design/quality/e2/scripts/e2.mjs" },
    status: "active; never bypassed",
    aliases: ["cost lock", "trava de custo", "paid-runtime lock"],
    queries: ["could this accidentally cost money", "isso pode gerar custo sem querer", "how is spending prevented"],
  },
];
